### ISSUE TITLE
Compression not working for time series that has a 'jump' in time dimension

### ISSUE THREAD

**Issue by vinaykakade** [jeromefroe/tsz-rs#9]
I have observed that the compression fails with an error if there are suddenly relatively large differences in the time dimension in the time series.

For example, if in the integration test in `lib.rs`, if `Data` is changed to

```
const DATA: &'static str = "0,1.0
1,1.0
5000,1.0
";
```

then the test fails with the below error:
```
thread 'tests::integration_test' panicked at 'attempt to subtract with overflow', test stream::buffered_read::tests::read_byte ... src/encode/std_encoder.rsok:
59:22test stream::buffered_read::tests::read_mixed ... 
ok
stack backtrace:
test stream::buffered_write::tests::write_bit ... ok
test stream::buffered_write::tests::write_bits ... ok
test stream::buffered_write::tests::write_byte ... ok
test stream::buffered_write::tests::write_mixed ... ok
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: tsz::encode::std_encoder::StdEncoder<T>::write_first
             at ./src/encode/std_encoder.rs:59:22
   4: <tsz::encode::std_encoder::StdEncoder<T> as tsz::encode::Encode>::encode
             at ./src/encode/std_encoder.rs:164:13
   5: tsz::tests::integration_test
             at ./src/lib.rs:227:13
   6: tsz::tests::integration_test::{{closure}}
             at ./src/lib.rs:212:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::integration_test ... FAILED
```

@jeromefroe - can you please take a look?

**Comment by jeromefroe** [comment]
@vinaykakade I believe you need to update the start time of the encoder: https://github.com/jeromefroe/tsz-rs/blob/0d237173f12b2e59df33004a45798c2ac1c6b62f/src/lib.rs#L197

The encoder only supports data streams of increasing time stamps so when you changed the test data to begin with a timestamp of 0 that timestamp is in fact before the encoder's start time.

**Comment by vinaykakade** [comment]
Thanks @jeromefroe. After changing the `StdEncoder` to start from `0`, the assertion in the test still fails. This does reproduce for other similar examples, where there is relatively large gap in the time dimension.

Stack trace below:
```
running 1 test
thread 'tests::integration_test' panicked at 'assertion failed: `(left == right)`
  left: `[DataPoint { time: 0, value: 1.0 }, DataPoint { time: 1, value: 1.0 }, DataPoint { time: 5000, value: 1.0 }]`,
 right: `[DataPoint { time: 0, value: 1.0 }, DataPoint { time: 1, value: 1.0 }, DataPoint { time: 4998, value: 1.0 }]`', src/lib.rs:254:9
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed::inner
   3: core::panicking::assert_failed
             at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/core/src/panicking.rs:143:5
   4: tsz::tests::integration_test
             at ./src/lib.rs:254:9
   5: tsz::tests::integration_test::{{closure}}
             at ./src/lib.rs:212:5
   6: core::ops::function::FnOnce::call_once
             at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::integration_test ... FAILED
```

**Comment by jeromefroe** [comment]
Oh, looks like it's panicking on the equality assertion now: https://github.com/jeromefroe/tsz-rs/blob/0d237173f12b2e59df33004a45798c2ac1c6b62f/src/lib.rs#L237

And indeed I can see in the output that the original values and those from the encoder are different:

```text
left: `[DataPoint { time: 0, value: 1.0 }, DataPoint { time: 1, value: 1.0 }, DataPoint { time: 5000, value: 1.0 }]`,
 right: `[DataPoint { time: 0, value: 1.0 }, DataPoint { time: 1, value: 1.0 }, DataPoint { time: 4998, value: 1.0 }]`'
```

I don't know when I'll have the chance to look into this more deeply but if you're curious, since it's the timestamp field that is wrong, here's the relevant code for encoding the timestamps: https://github.com/jeromefroe/tsz-rs/blob/0d237173f12b2e59df33004a45798c2ac1c6b62f/src/encode/std_encoder.rs#L77

and for decoding the timestamps: https://github.com/jeromefroe/tsz-rs/blob/0d237173f12b2e59df33004a45798c2ac1c6b62f/src/decode/std_decoder.rs#L82
